// TSX -> TS + HTML
// JSX => JS + HTML

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

// Sıfır bir nextjs projesi açıp 2 sayfalık kendinizi tanıtan bir websitesi geliştiriniz.
// 1- Ana sayfa
// 2- Projelerim sayfası

// API Çağrıları (Frontend)
// Dinamik Yapılar
// CSR - SSR